site_name: python-devtools
site_description: Python's missing debug print command and other development tools.
strict: false
site_url: https://python-devtools.helpmanual.io/

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
    primary: pink
    accent: pink

repo_name: samuelcolvin/python-devtools
repo_url: https://github.com/samuelcolvin/python-devtools

#
# FIXME: google_analytics is deprecated. This section must be replaced with
#        something like this instead:
#
# analytics:
#    gtag: G-123456
#
# Once this is replaced, re-enable strict mode at the top of this file.
#
# See https://github.com/mkdocs/mkdocs/issues/2252 for details.
#
google_analytics:
- 'UA-62733018-4'
- 'auto'

extra_css:
- 'theme/customization.css'

nav:
- Overview: index.md
- install.md
- usage.md
- history.md

markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- markdown_include.include:
    base_path: docs
- toc:
    permalink: 🔗
- admonition
- codehilite
- extra
- attr_list

plugins:
- search
- exclude:
    glob:
    - build/*
    - examples/*
    - requirements.txt
